# intercept: where y lies when x lies on 0 and so on
# co effecient when x incresed/decreae how much y increased\ decrease
# when y has more than two value it is multiclassification problem
# score check what percentage accuracy is

# logistic ,knn,naive bayes

In [89]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler 
from sklearn.preprocessing import MinMaxScaler # mostly used normalization  and image processing
import warnings
warnings=warnings.filterwarnings('ignore')



# featur scaling is used when whole data in numeric form

In [90]:
df=pd.read_csv("C:\\Users\\Mr\\Desktop\\location\\df3.csv")

In [91]:
df.describe().round(2)

gender  Occupation_Corporate  Occupation_Housewife  \
count  287162.00             287162.00             287162.00   
mean        0.82                  0.21                  0.23   
std         0.38                  0.41                  0.42   
min         0.00                  0.00                  0.00   
25%         1.00                  0.00                  0.00   
50%         1.00                  0.00                  0.00   
75%         1.00                  0.00                  0.00   
max         1.00                  1.00                  1.00   

       Occupation_Others  Occupation_Student  self_employed_Yes  \
count          287162.00           287162.00           287162.0   
mean                0.18                0.21                0.1   
std                 0.38                0.41                0.3   
min                 0.00                0.00                0.0   
25%                 0.00                0.00                0.0   
50%                 0.00                0.00                0.0   
75%                 0.00                0.00                0.0   
max                 1.00                1.00                1.0   

       family_history_Yes  treatment_Yes  Social_Weakness_No  \
count           287162.00       287162.0           287162.00   
mean                 0.40            0.5                0.33   
std                  0.49            0.5                0.47   
min                  0.00            0.0                0.00   
25%                  0.00            0.0                0.00   
50%                  0.00            1.0                0.00   
75%                  1.00            1.0                1.00   
max                  1.00            1.0                1.00   

       Social_Weakness_Yes  Coping_Struggles_Yes  Growing_Stress  \
count            287162.00             287162.00       287162.00   
mean                  0.31                  0.47            1.00   
std                   0.46                  0.50            0.83   
min                   0.00                  0.00            0.00   
25%                   0.00                  0.00            0.00   
50%                   0.00                  0.00            1.00   
75%                   1.00                  1.00            2.00   
max                   1.00                  1.00            2.00   

       Mood_Swings_le  Days_Indoors_le  Work_Interest_le  
count       287162.00        287162.00         287162.00  
mean             1.03             3.02              0.93  
std              0.81             1.42              0.81  
min              0.00             1.00              0.00  
25%              0.00             2.00              0.00  
50%              1.00             3.00              1.00  
75%              2.00             4.00              2.00  
max              2.00             5.00              2.00

In [92]:
df.tail()

gender  Occupation_Corporate  Occupation_Housewife  Occupation_Others  \
287157       1                     0                     0                  0   
287158       1                     0                     0                  0   
287159       1                     0                     0                  0   
287160       1                     0                     0                  0   
287161       1                     0                     0                  0   

        Occupation_Student  self_employed_Yes  family_history_Yes  \
287157                   0                  1                   1   
287158                   0                  0                   1   
287159                   0                  0                   1   
287160                   0                  0                   1   
287161                   0                  0                   1   

        treatment_Yes  Social_Weakness_No  Social_Weakness_Yes  \
287157              1                   0                    0   
287158              1                   0                    0   
287159              0                   0                    0   
287160              1                   0                    0   
287161              1                   0                    0   

        Coping_Struggles_Yes  Growing_Stress  Mood_Swings_le  Days_Indoors_le  \
287157                     1               1               1                2   
287158                     1               1               1                2   
287159                     1               1               1                2   
287160                     1               1               1                2   
287161                     1               1               1                2   

        Work_Interest_le  
287157                 0  
287158                 0  
287159                 0  
287160                 0  
287161                 0

In [93]:
df.dtypes

gender                  int64
Occupation_Corporate    int64
Occupation_Housewife    int64
Occupation_Others       int64
Occupation_Student      int64
self_employed_Yes       int64
family_history_Yes      int64
treatment_Yes           int64
Social_Weakness_No      int64
Social_Weakness_Yes     int64
Coping_Struggles_Yes    int64
Growing_Stress          int64
Mood_Swings_le          int64
Days_Indoors_le         int64
Work_Interest_le        int64
dtype: object

In [94]:
#df2=df[['Mood_Swings_le','Days_Indoors_le']]

# scaling is applied on only indepedent variables

In [95]:
# df2=df.fillna(df.mean())

In [96]:
X=df.drop('Growing_Stress',axis=1)
X

gender  Occupation_Corporate  Occupation_Housewife  Occupation_Others  \
0            0                     1                     0                  0   
1            0                     1                     0                  0   
2            0                     1                     0                  0   
3            0                     1                     0                  0   
4            0                     1                     0                  0   
...        ...                   ...                   ...                ...   
287157       1                     0                     0                  0   
287158       1                     0                     0                  0   
287159       1                     0                     0                  0   
287160       1                     0                     0                  0   
287161       1                     0                     0                  0   

        Occupation_Student  self_employed_Yes  family_history_Yes  \
0                        0                  0                   1   
1                        0                  0                   1   
2                        0                  0                   0   
3                        0                  0                   1   
4                        0                  0                   0   
...                    ...                ...                 ...   
287157                   0                  1                   1   
287158                   0                  0                   1   
287159                   0                  0                   1   
287160                   0                  0                   1   
287161                   0                  0                   1   

        treatment_Yes  Social_Weakness_No  Social_Weakness_Yes  \
0                   1                   0                    1   
1                   1                   0                    1   
2                   1                   0                    1   
3                   1                   0                    1   
4                   0                   0                    1   
...               ...                 ...                  ...   
287157              1                   0                    0   
287158              1                   0                    0   
287159              0                   0                    0   
287160              1                   0                    0   
287161              1                   0                    0   

        Coping_Struggles_Yes  Mood_Swings_le  Days_Indoors_le  \
0                          0               2                4   
1                          0               2                4   
2                          0               2                4   
3                          0               2                4   
4                          0               2                4   
...                      ...             ...              ...   
287157                     1               1                2   
287158                     1               1                2   
287159                     1               1                2   
287160                     1               1                2   
287161                     1               1                2   

        Work_Interest_le  
0                      0  
1                      0  
2                      0  
3                      0  
4                      0  
...                  ...  
287157                 0  
287158                 0  
287159                 0  
287160                 0  
287161                 0  

[287162 rows x 14 columns]

In [97]:
Y=df['Growing_Stress']
Y

0         2
1         2
2         2
3         2
4         2
         ..
287157    1
287158    1
287159    1
287160    1
287161    1
Name: Growing_Stress, Length: 287162, dtype: int64

In [98]:
from sklearn.model_selection import train_test_split

In [99]:
x_train,x_test,y_train,y_test=train_test_split(X,Y,test_size=0.3,random_state=42)

In [100]:
x_test.keys()

Index(['gender', 'Occupation_Corporate', 'Occupation_Housewife',
       'Occupation_Others', 'Occupation_Student', 'self_employed_Yes',
       'family_history_Yes', 'treatment_Yes', 'Social_Weakness_No',
       'Social_Weakness_Yes', 'Coping_Struggles_Yes', 'Mood_Swings_le',
       'Days_Indoors_le', 'Work_Interest_le'],
      dtype='object')

In [101]:
x_train.shape

(201013, 14)

In [102]:
y_train.shape

(201013,)

# minmax scaler

In [103]:
mmc=MinMaxScaler()

In [104]:
mmc.fit(x_train)

MinMaxScaler()

In [105]:
x_train_mmc=mmc.transform(x_train)
x_test_mmc=mmc.transform(x_test)

In [106]:
x_train_mmc

array([[1.  , 0.  , 0.  , ..., 0.5 , 0.  , 1.  ],
       [1.  , 0.  , 0.  , ..., 0.5 , 0.75, 0.5 ],
       [1.  , 0.  , 0.  , ..., 0.5 , 0.75, 1.  ],
       ...,
       [1.  , 0.  , 0.  , ..., 0.  , 0.5 , 0.5 ],
       [1.  , 1.  , 0.  , ..., 0.5 , 0.75, 0.  ],
       [1.  , 0.  , 0.  , ..., 1.  , 1.  , 1.  ]])

In [107]:
x_train_mmc=pd.DataFrame(x_train_mmc,columns=['gender', 'Occupation_Corporate', 'Occupation_Housewife',
       'Occupation_Others', 'Occupation_Student', 'self_employed_Yes',
       'family_history_Yes', 'treatment_Yes', 'Social_Weakness_No',
       'Social_Weakness_Yes', 'Coping_Struggles_Yes', 'Mood_Swings_le',
       'Days_Indoors_le', 'Work_Interest_le'])
      

In [108]:
x_test_mmc=pd.DataFrame(x_test_mmc,columns=['gender', 'Occupation_Corporate', 'Occupation_Housewife',
       'Occupation_Others', 'Occupation_Student', 'self_employed_Yes',
       'family_history_Yes', 'treatment_Yes', 'Social_Weakness_No',
       'Social_Weakness_Yes', 'Coping_Struggles_Yes', 'Mood_Swings_le',
       'Days_Indoors_le', 'Work_Interest_le'])
      

In [109]:
x_train_mmc.describe().round(2)

gender  Occupation_Corporate  Occupation_Housewife  \
count  201013.00             201013.00             201013.00   
mean        0.82                  0.21                  0.23   
std         0.38                  0.41                  0.42   
min         0.00                  0.00                  0.00   
25%         1.00                  0.00                  0.00   
50%         1.00                  0.00                  0.00   
75%         1.00                  0.00                  0.00   
max         1.00                  1.00                  1.00   

       Occupation_Others  Occupation_Student  self_employed_Yes  \
count          201013.00           201013.00           201013.0   
mean                0.18                0.21                0.1   
std                 0.39                0.41                0.3   
min                 0.00                0.00                0.0   
25%                 0.00                0.00                0.0   
50%                 0.00                0.00                0.0   
75%                 0.00                0.00                0.0   
max                 1.00                1.00                1.0   

       family_history_Yes  treatment_Yes  Social_Weakness_No  \
count           201013.00       201013.0           201013.00   
mean                 0.39            0.5                0.33   
std                  0.49            0.5                0.47   
min                  0.00            0.0                0.00   
25%                  0.00            0.0                0.00   
50%                  0.00            1.0                0.00   
75%                  1.00            1.0                1.00   
max                  1.00            1.0                1.00   

       Social_Weakness_Yes  Coping_Struggles_Yes  Mood_Swings_le  \
count            201013.00             201013.00       201013.00   
mean                  0.31                  0.47            0.52   
std                   0.46                  0.50            0.41   
min                   0.00                  0.00            0.00   
25%                   0.00                  0.00            0.00   
50%                   0.00                  0.00            0.50   
75%                   1.00                  1.00            1.00   
max                   1.00                  1.00            1.00   

       Days_Indoors_le  Work_Interest_le  
count        201013.00         201013.00  
mean              0.50              0.47  
std               0.36              0.40  
min               0.00              0.00  
25%               0.25              0.00  
50%               0.50              0.50  
75%               0.75              1.00  
max               1.00              1.00

In [110]:
#sns.pairplot(x_train)

In [111]:
#sns.pairplot(x_train_mmc)

## main problem to detect anyone has depression or not using supervised linear algorithm

# linear Regresion ML model training

In [112]:
from sklearn.linear_model import LinearRegression

In [113]:
lr=LinearRegression()

In [114]:
lr.fit(x_train_mmc,y_train)

LinearRegression()

In [115]:
lr.coef_ # beta values according to features

array([-0.12411757,  0.07304255, -0.10251117, -0.0822511 , -0.04960604,
        0.00262666,  0.00242762, -0.00021277, -0.02844142,  0.0543022 ,
        0.0282214 ,  0.08533331, -0.08465757,  0.16567136])

In [116]:
lr.intercept_

1.0337031168905113

# PREDICT value and test

In [117]:
x_test_mmc.iloc[0, :]


gender                  1.00
Occupation_Corporate    0.00
Occupation_Housewife    1.00
Occupation_Others       0.00
Occupation_Student      0.00
self_employed_Yes       1.00
family_history_Yes      0.00
treatment_Yes           0.00
Social_Weakness_No      0.00
Social_Weakness_Yes     1.00
Coping_Struggles_Yes    1.00
Mood_Swings_le          0.00
Days_Indoors_le         0.75
Work_Interest_le        0.00
Name: 0, dtype: float64

In [118]:
lr.predict([x_test_mmc.iloc[0, :]])

array([0.82873144])

In [119]:
lr.predict(x_test_mmc)

array([0.82873144, 1.04177179, 1.12594743, ..., 1.06654166, 0.87888921,
       0.88181986])

In [120]:
y_test

246181    1
138065    0
13623     0
157622    0
46387     0
         ..
214846    0
174137    2
163168    2
58124     2
179625    2
Name: Growing_Stress, Length: 86149, dtype: int64

In [121]:
lr.score(x_test_mmc,y_test)

0.018809681597506844

In [122]:
from sklearn.preprocessing import PolynomialFeatures
poly_reg=PolynomialFeatures(degree=3)

In [123]:
poly_reg.fit(x_train_mmc)

PolynomialFeatures(degree=3)

In [124]:
x_train_mmc_poly=poly_reg.transform(x_train_mmc)
x_test_mmc_poly=poly_reg.transform(x_test_mmc)

In [125]:
x_test_mmc_poly.shape,x_train_mmc_poly.shape

((86149, 680), (201013, 680))

In [126]:
from sklearn.linear_model import LinearRegression
lr=LinearRegression()

In [127]:
lr.fit(x_train_mmc_poly,y_train)

LinearRegression()

In [128]:
lr.score(x_test_mmc_poly,y_test)

0.3326645011626157

In [129]:
lr.predict([x_test_mmc_poly[0,:]])

array([0.94549561])

In [130]:
y_prd=lr.predict(x_test_mmc_poly)
y_prd


array([0.94509888, 0.69363403, 0.89089966, ..., 1.04812622, 0.94558716,
       1.40597534])

In [131]:
y_test

246181    1
138065    0
13623     0
157622    0
46387     0
         ..
214846    0
174137    2
163168    2
58124     2
179625    2
Name: Growing_Stress, Length: 86149, dtype: int64

In [132]:
from sklearn.metrics import mean_squared_error
mse=mean_squared_error(y_test,y_prd)
rms=np.sqrt(mse)
mse,rms

(0.45566649028123757, 0.6750307328420222)

# logistic regression 