In [2]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn.metrics import precision_score, recall_score, f1_score #roc_curve,roc_auc_score use for binary classificatioon



In [3]:
df=pd.read_csv("C:\\Users\\Mr\\Desktop\\\location\\mental_health.csv")

In [4]:
last_indices = df.index[-200000:]

df = df.drop(index=last_indices)

In [5]:
df.head()

gender  Occupation_Corporate  Occupation_Housewife  Occupation_Others  \
0       0                     1                     0                  0   
1       0                     1                     0                  0   
2       0                     1                     0                  0   
3       0                     1                     0                  0   
4       0                     1                     0                  0   

   Occupation_Student  self_employed_Yes  family_history_Yes  treatment_Yes  \
0                   0                  0                   1              1   
1                   0                  0                   1              1   
2                   0                  0                   0              1   
3                   0                  0                   1              1   
4                   0                  0                   0              0   

   Social_Weakness_No  Social_Weakness_Yes  Coping_Struggles_Yes  \
0                   0                    1                     0   
1                   0                    1                     0   
2                   0                    1                     0   
3                   0                    1                     0   
4                   0                    1                     0   

   Growing_Stress  Mood_Swings_le  Days_Indoors_le  Work_Interest_le  
0               2               2                4                 0  
1               2               2                4                 0  
2               2               2                4                 0  
3               2               2                4                 0  
4               2               2                4                 0

In [7]:
last_indices = df.index[-30000:]

df = df.drop(index=last_indices)

In [8]:
df.shape

(27162, 15)

In [9]:
x=df.drop('Growing_Stress',axis=1)

In [10]:
y=df['Growing_Stress']

In [11]:
from sklearn.model_selection import train_test_split

In [12]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=42)

In [13]:
mmc=MinMaxScaler()

In [14]:
mmc.fit(x_train)

MinMaxScaler()

In [15]:
y_test

26169    2
1427     2
6700     2
7759     0
20475    1
        ..
20520    1
14152    0
12795    2
21163    2
25886    2
Name: Growing_Stress, Length: 8149, dtype: int64

In [16]:
x_train_mmc=mmc.transform(x_train)
x_test_mmc=mmc.transform(x_test)

In [18]:
x_train_mmc=pd.DataFrame(x_train_mmc,columns=['Gender_Male', 'Occupation_Corporate', 'Occupation_Housewife',
       'Occupation_Others', 'Occupation_Student', 'self_employed_Yes',
       'family_history_Yes', 'treatment_Yes', 'Social_Weakness_No',
       'Social_Weakness_Yes', 'Coping_Struggles_Yes', 'Mood_Swings_le',
       'Days_Indoors_le', 'Work_Interest_le'])

In [16]:
#x_test_mmc=pd.DataFrame(x_test_mmc,columns=['Gender_Male', 'Occupation_Corporate', 'Occupation_Housewife',
       #'Occupation_Others', 'Occupation_Student', 'self_employed_Yes',
       #'family_history_Yes', 'treatment_Yes', 'Social_Weakness_No',
       #'Social_Weakness_Yes', 'Coping_Struggles_Yes', 'Mood_Swings_le',
       #'Days_Indoors_le', 'Work_Interest_le'])

In [19]:
from sklearn.svm import SVC

In [20]:
svc_rbf=SVC(kernel='rbf')

In [21]:
svc_rbf.fit(x_train_mmc,y_train)

SVC()

In [22]:
svc_rbf.score(x_test_mmc,y_test)

c:\Users\Mr\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  warnings.warn(


0.8626825377346914

In [23]:
#svr_rbf.predict([x_test_mmc.iloc[0]])  # Use iloc to access the first row and reshape with correct arguments

In [24]:
svc_rbf.predict([x_test_mmc[0]])

c:\Users\Mr\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  warnings.warn(


array([2], dtype=int64)

In [25]:
x_test_mmc[0] #when data in aray form

array([0. , 0. , 1. , 0. , 0. , 0. , 1. , 0. , 0. , 1. , 1. , 0.5, 0. ,
       1. ])

In [24]:
#x_test_mmc.iloc[0] # when data in datafram form

In [26]:
y_predt=svc_rbf.predict(x_test_mmc)
y_predt

c:\Users\Mr\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  warnings.warn(


array([2, 2, 2, ..., 2, 2, 2], dtype=int64)

In [27]:
accuracy_score(y_test,y_predt)

0.8626825377346914

In [28]:

svc_poly=SVC(kernel='poly',degree=3)



In [29]:
svc_poly.fit(x_train_mmc,y_train)
svc_poly.score(x_test_mmc,y_test)

c:\Users\Mr\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  warnings.warn(


0.8805988464842311

In [30]:
from sklearn.ensemble import RandomForestClassifier

In [31]:
Rf_c=RandomForestClassifier()

In [32]:
Rf_c.fit(x_train_mmc,y_train)

RandomForestClassifier()

In [33]:
Rf_c.score(x_test_mmc,y_test)

c:\Users\Mr\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


0.9777886857283102

In [34]:
y_pred_rf=Rf_c.predict(x_test_mmc)

c:\Users\Mr\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


In [35]:
accuracy_score(y_test,y_pred_rf)

0.9777886857283102

In [36]:
confusion_matrix(y_test,y_pred_rf)

array([[2328,    7,   28],
       [  55, 2156,   25],
       [  10,   56, 3484]], dtype=int64)

In [37]:
f1_score(y_test,y_pred_rf,average='micro')

0.9777886857283102

In [38]:
from sklearn.neighbors import KNeighborsClassifier
KNn=KNeighborsClassifier()

In [39]:
KNn.fit(x_train_mmc,y_train)

KNeighborsClassifier()

In [40]:
KNn.score(x_test_mmc,y_test)

c:\Users\Mr\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  warnings.warn(


0.9750889679715302

In [41]:
y_pred_kNn=KNn.predict(x_test_mmc)

c:\Users\Mr\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  warnings.warn(


In [42]:
accuracy_score(y_test,y_pred_kNn)

0.9750889679715302

# Classification report


In [43]:
print(classification_report(y_test,y_pred_kNn))

              precision    recall  f1-score   support

           0       0.97      0.98      0.97      2363
           1       0.96      0.96      0.96      2236
           2       0.99      0.98      0.98      3550

    accuracy                           0.98      8149
   macro avg       0.97      0.97      0.97      8149
weighted avg       0.98      0.98      0.98      8149



# cross validation

In [44]:
from sklearn.model_selection import cross_val_score


In [45]:
cross_val = cross_val_score(estimator=KNn, X=x_train_mmc, y=y_train, cv=5)
print("cross validation",cross_val)
print("cross validation mean",cross_val.mean())


cross validation [0.96555351 0.96634236 0.96607941 0.96607049 0.96028406]
cross validation mean 0.9648659665816585


# saving our model

In [46]:
import pickle
pickle.dump(KNn,open('model.pkl','wb')) #wb=write binary
model=pickle.load(open('model.pkl','rb')) #rb=read binary
y_pred=model.predict(x_test_mmc)
print("accuracy score",accuracy_score(y_test,y_pred))
print("recall score",recall_score(y_test,y_pred,average='macro'))
print("f1 score",f1_score(y_test,y_pred,average='macro'))
print("confusion matrix",confusion_matrix(y_test,y_pred))

c:\Users\Mr\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  warnings.warn(


accuracy score 0.9750889679715302
recall score 0.973828120030472
f1 score 0.9734112964269431
confusion matrix [[2307   49    7]
 [  40 2155   41]
 [  30   36 3484]]
